name: Test Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Print timestamp
        run: |
          echo "Workflow partito"
          echo "Evento: ${{ github.event_name }}"
          date -u
